grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 2
    verbose: 2
model_selection:
  module_0:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      min_samples_split: 2
    search_param_grid:
      min_samples_split:
      - 2
      - 8
      - 15
  module_1:
    class: XGBClassifier
    module: xgboost 
    params:
      n_estimators: 20
    search_param_grid:
      n_estimators:
        - 100
        - 200
        - 300
